apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      serviceAccountName: test-user-account
      containers:
      - image: sakibalamin/demo-app:0.0.2
        name: demo-app
        imagePullPolicy: Always
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets-store/sql-creds"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-db-provider"
              