apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: sql
  namespace: db
spec:
  version: 8.0.27
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut