apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-kv
  namespace: trial
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: vault-kv-storage