apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicyBinding
metadata:
  name: reader-role
  namespace: demo
spec:
  vaultRef:
    name: vault
  policies:
    - ref: reader-policy
  subjectRef:
    oidc:
      path: oidc
      boundAudiences: 
      - "aFSrk3w06WsQqyjA30HvhbbJIR1VBidU"
      allowedRedirectUris: 
      - "http://localhost:8200/ui/vault/auth/oidc/oidc/callback"
      - "http://localhost:8250/oidc/callback"
      userClaim: "sub"
