apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: reader-policy
  namespace: demo
spec:
  vaultRef:
    name: vault
  policyDocument: |
    path "/kv/*" {
      capabilities = ["read", "list"]
    }
