apiVersion: engine.kubevault.com/v1alpha1
kind: SecretRoleBinding
metadata:
  name: secret-r-binding
  namespace: dev
spec:
  roles:
    - kind: MongoDBRole
      name: mongo-superuser-role
  subjects:
    - kind: ServiceAccount
      name: test-user-account 
      namespace: test
