apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  creationTimestamp: null
  name: mongo-secret-provider
  namespace: test
spec:
  parameters:
    objects: |
      - objectName: mongo-user
        secretKey: username
        secretPath: /k8s.kubevault.com.mongodb.dev.mongo-secret-engine/creds/k8s.kubevault.com.dev.mongo-superuser-role
      - objectName: mongo-pass
        secretKey: password
        secretPath: /k8s.kubevault.com.mongodb.dev.mongo-secret-engine/creds/k8s.kubevault.com.dev.mongo-superuser-role
    roleName: k8s.kubevault.com.demo.srb-dev-secret-r-binding
    vaultAddress: http://vault.demo:8200
    vaultSkipTLSVerify: "true"
  provider: vault
status: {}

