apiVersion: engine.kubevault.com/v1alpha1
kind: SecretAccessRequest
metadata:
  name: mongo-cred-req
  namespace: dev
spec:
  roleRef:
    kind: MongoDBRole
    name: mongo-superuser-role
  subjects:
    - kind: ServiceAccount
      name: test-user-account 
      namespace: test
