apiVersion: engine.kubevault.com/v1alpha1
kind: SecretAccessRequest
metadata:
  name: mysql-cred-req
  namespace: dev
spec:
  roleRef:
    kind: MySQLRole
    name: superuser-role
  subjects:
    - kind: ServiceAccount
      name: superuser-sa 
      namespace: test
