apiVersion: engine.kubevault.com/v1alpha1
kind: MongoDBRole
metadata:
  name: reader-role
  namespace: dev
spec:
  secretEngineRef:
    name: mongo-secret-engine
  creationStatements:
    - '{ "db": "mydb", "roles": [{"role": "read"}] }'
