apiVersion: engine.kubevault.com/v1alpha1
kind: SecretRoleBinding
metadata:
  name: secret-r-binding
  namespace: dev
spec:
  roles:
    - kind: MongoDBRole
      name: reader-role
  subjects:
    - kind: ServiceAccount
      name: app-user
      namespace: app
