apiVersion: engine.kubevault.com/v1alpha1
kind: SecretAccessRequest
metadata:
  name: read-access-req
  namespace: dev
spec:
  roleRef:
    kind: RedisRole
    name: read-role
  subjects:
    - kind: ServiceAccount
      name: read-user
      namespace: user
