apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-db-provider
  namespace: app
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.demo:8200"
    roleName: k8s.57d29b27-a15c-4f9c-b0c2-c3e11cdd9418.demo.srb-dev-secret-role-binding
    objects: |
      - objectName: "redis-creds-username"
        secretPath: "/k8s.57d29b27-a15c-4f9c-b0c2-c3e11cdd9418.redis.dev.redis-secret-engine/creds/k8s.57d29b27-a15c-4f9c-b0c2-c3e11cdd9418.dev.read-role"
        secretKey: "username"
      - objectName: "redis-creds-password"
        secretPath: "/k8s.57d29b27-a15c-4f9c-b0c2-c3e11cdd9418.redis.dev.redis-secret-engine/creds/k8s.57d29b27-a15c-4f9c-b0c2-c3e11cdd9418.dev.read-role"
                      # $secre-engine-path/creds/$rolename
        secretKey: "password"