apiVersion: engine.kubevault.com/v1alpha1
kind: SecretRoleBinding
metadata:
  name: secret-role-binding
  namespace: dev
spec:
  roles:
    - kind: RedisRole
      name: read-role
  subjects:
    - kind: ServiceAccount
      name: app-user
      namespace: app